const cols=['Opco','SR Reporting Month','SR Date','SR Incident Date','SR Creation Channel','SR Number','Customer Name','Customer No','GL Product Code','GL Product Level 2','GL Product Level 4','GL Product Level 6','IB Serial Number','SR Type','SR Status','SR Created By','SR Group Owner','CSE Name','CSE Group Name','Contract Type','SR Problem Summary','SR Resolution Code','SR Resolution Summary','Task Number','Task Type','Task Status','Task Description','Debrief Header CSE Comments','Actual CSE Name','Inventory Item Code','Debrief Header Arrival Time','Debrief Header Departure Time'];
const customers=[['한빛전자','C-1001'],['미래테크','C-1002'],['세진정밀','C-1003'],['동아메디칼','C-1004'],['에이스솔루션','C-1005']];
const types=['용지걸림','화질 불량','소모품 교체','스캔 오류','출력 오류','드라이버 설치','네트워크 연결','사용 문의'];
const problems=['출력 중 용지가 내부에서 걸림','출력물에 줄이 생기고 농도가 고르지 않음','토너 또는 드럼 교체 주기 도래','스캔 전송 중 오류가 발생함','작업 중 오류 코드 E-204 발생','PC에서 프린터 드라이버 설치 요청','복합기와 사내 네트워크 연결 불가','장비 기본 사용 방법 문의'];
const resolutions=['급지부 이물 제거 및 롤러 교체','현장 점검 후 화상 품질 조정','소모품 교체 완료','스캔 설정 초기화 및 테스트','제어보드 점검 후 정상 작동','드라이버 설치 및 출력 테스트','IP 재설정 및 네트워크 연결','사용 방법 안내'];
const names=['김도윤','박서연','이준호','최하은'],hardwareTypes=['용지걸림','화질 불량','소모품 교체','출력 오류'];
const $=id=>document.getElementById(id),pad=n=>String(n).padStart(2,'0'),iso=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
const categoryOf=t=>hardwareTypes.includes(t)?'하드웨어':'소프트웨어';
const channelOf=v=>{let x=String(v||'').trim().toLowerCase();return x==='email'?'Email':x==='phone'?'Phone':x==='web'?'Web':String(v||'미분류').trim()||'미분류'};
let data=[],dataSource='테스트 데이터',audit=[],currentUser=null;
function decorate(r){r['SR Creation Channel']=channelOf(r['SR Creation Channel']);r['IB Serial Number']=String(r['IB Serial Number']||'').replace(/\D/g,'').slice(-6);r._date=new Date(r['SR Date']||r['SR Incident Date']||Date.now());if(Number.isNaN(r._date.getTime()))r._date=new Date();r._machine=r['IB Serial Number'];r._category=categoryOf(r['SR Type']);return r}
function fakeData(){let out=[],base=new Date(2026,3,1);for(let i=0;i<240;i++){let d=new Date(base);d.setDate(d.getDate()+Math.min(169,Math.floor(i*169/239)));let ci=i%5,mi=(i*7)%18+1,type=types[i%types.length],status=i%7===0?'진행중':i%19===0?'취소':'완료',hw=hardwareTypes.includes(type),r={};cols.forEach(c=>r[c]='');Object.assign(r,{'Opco':'Korea','SR Reporting Month':`${d.getFullYear()}-${pad(d.getMonth()+1)}`,'SR Date':iso(d),'SR Incident Date':iso(new Date(d.getTime()-86400000)),'SR Creation Channel':['Phone','Email','Web'][i%3],'SR Number':`SR-26${pad((i%900)+100)}`,'Customer Name':customers[ci][0],'Customer No':customers[ci][1],'IB Serial Number':String(100000+ci*10000+mi),'SR Type':type,'SR Status':status,'SR Created By':names[i%4],'SR Group Owner':'TSC '+(i%2?'East':'Central'),'CSE Name':names[(i+1)%4],'CSE Group Name':'Field Service','Contract Type':i%3?'Standard':'Premium','SR Problem Summary':problems[i%8],'SR Resolution Code':`R-${i%4+1}`,'SR Resolution Summary':status==='완료'?resolutions[i%8]:'담당자 확인 중','Task Number':`TK-${5000+i}`,'Task Type':hw?'Field Visit':'Remote Support','Task Status':status,'Task Description':problems[i%8],'Debrief Header CSE Comments':hw?(status==='완료'?resolutions[i%8]+' / 현장 테스트 완료':'방문 일정 조율 중'):'원격으로 설정 및 사용 방법 안내','Actual CSE Name':hw?names[(i+2)%4]:'-'});out.push(decorate(r))}return out}
function statusHtml(s){return `<span class="status ${s==='완료'?'done':s==='취소'?'cancel':'open'}">${s||'미분류'}</span>`}
function bindRows(id){document.querySelectorAll(`#${id} tr[data-id]`).forEach(tr=>tr.onclick=()=>openDetail(data.find(r=>r['SR Number']===tr.dataset.id)))}
function openDetail(r){if(!r)return;let fields=[['SR 번호',r['SR Number']],['접수일',r['SR Date']],['고객사',r['Customer Name']],['기계번호',r['IB Serial Number']],['콜 구분',r._category],['콜 유형',r['SR Type']],['인입 채널',r['SR Creation Channel']],['상태',r['SR Status']],['Task 상태',r['Task Status']],['상담원',r['SR Created By']],['방문 엔지니어',r['Actual CSE Name']],['문제 요약',r['SR Problem Summary']],['현장 조치 내용',r['Debrief Header CSE Comments']],['처리 결과',r['SR Resolution Summary']]];$('modal-content').innerHTML=`<h2 class="detail-title">${r['SR Number']} 콜 상세</h2><p class="detail-sub">${r['Customer Name']} · 기계번호 ${r['IB Serial Number']}</p><div class="detail-grid">${fields.map(f=>`<div class="detail-cell"><small>${f[0]}</small><div>${f[1]||'-'}</div></div>`).join('')}</div>`;$('detail-modal').classList.remove('hidden')}
function latestDate(){return data.length?new Date(Math.max(...data.map(r=>r._date.getTime()))):new Date()}
function renderKPIs(){let total=data.length,complete=data.filter(r=>r['SR Status']==='완료').length,hw=data.filter(r=>r._category==='하드웨어').length,latest=latestDate(),start=new Date(latest.getFullYear(),latest.getMonth(),1),prevStart=new Date(latest.getFullYear(),latest.getMonth()-1,1),prevEnd=new Date(latest.getFullYear(),latest.getMonth(),0),cur=data.filter(r=>r._date>=start).length,prev=data.filter(r=>r._date>=prevStart&&r._date<=prevEnd).length,repeat=data.filter((r,i)=>data.some((x,j)=>j!==i&&x._machine===r._machine&&Math.abs(r._date-x._date)<=2592000000)).length;$('kpi-total').textContent=total.toLocaleString();$('hero-total').textContent=cur;$('kpi-hardware').textContent=hw;$('kpi-software').textContent=total-hw;$('hardware-ratio').style.width=(total?hw/total*100:0)+'%';$('software-ratio').style.width=(total?((total-hw)/total*100):0)+'%';$('kpi-completion').textContent=(total?Math.round(complete/total*100):0)+'%';$('kpi-repeat').textContent=repeat;$('data-source-label').textContent=`${dataSource} · 전체 ${total.toLocaleString()}건`;$('period-label').textContent=`${latest.getFullYear()}년 ${latest.getMonth()+1}월 기준`;$('period-comparison').textContent=prev?`전월 ${prev}건 → 당월 ${cur}건 (${Math.round((cur-prev)/prev*100)}%)`:'전월 데이터 없음'}
function renderChart(){let mode=$('chart-filter').value,latest=latestDate(),months=[];for(let n=5;n>=0;n--){let d=new Date(latest.getFullYear(),latest.getMonth()-n,1),next=new Date(d.getFullYear(),d.getMonth()+1,1),rows=data.filter(r=>r._date>=d&&r._date<next&&(mode==='all'||r._category===(mode==='hardware'?'하드웨어':'소프트웨어')));months.push({label:`${d.getMonth()+1}월`,count:rows.length})}let max=Math.max(1,...months.map(x=>x.count));$('bar-chart').innerHTML=months.map(x=>`<div class="bar-item"><span class="bar-value">${x.count}</span><div class="bar ${mode==='hardware'?'hardware':mode==='software'?'software':''}" style="height:${Math.max(8,x.count/max*135)}px"></div><span class="bar-label">${x.label}</span></div>`).join('')}
function renderTypes(){let counts={};data.forEach(r=>counts[r['SR Type']||'미분류']=(counts[r['SR Type']||'미분류']||0)+1);let items=Object.entries(counts).sort((a,b)=>b[1]-a[1]).slice(0,8),max=Math.max(1,...items.map(x=>x[1]));$('type-list').innerHTML=items.map(([k,v])=>{let c=categoryOf(k);return `<div class="type-row"><div class="type-label"><span><b class="type-badge ${c==='하드웨어'?'hardware':'software'}">${c}</b>${k}</span><b>${v}건</b></div><div class="type-track"><div class="type-fill ${c==='하드웨어'?'hardware':'software'}" style="width:${v/max*100}%"></div></div></div>`}).join('')}
function renderChannels(){let order=['Email','Phone','Web'],counts={};data.forEach(r=>counts[channelOf(r['SR Creation Channel'])]=(counts[channelOf(r['SR Creation Channel'])]||0)+1);let total=data.length||1,max=Math.max(1,...order.map(k=>counts[k]||0));$('channel-list').innerHTML=order.map(k=>{let c=counts[k]||0;return `<div class="channel-card ${k.toLowerCase()}"><div class="channel-card-head"><span>${k}</span><b>${c}건</b></div><div class="channel-track"><i style="width:${c/max*100}%"></i></div><small>${Math.round(c/total*100)}% · 전체 콜 대비</small></div>`}).join('')}
function renderDashboardData(){let cat=$('dashboard-category-filter').value,ch=$('dashboard-channel-filter').value,rows=data.filter(r=>(cat==='all'||r._category===(cat==='hardware'?'하드웨어':'소프트웨어'))&&(ch==='all'||r['SR Creation Channel']===ch)).sort((a,b)=>b._date-a._date).slice(0,30);$('dashboard-data-table').innerHTML=rows.map(r=>`<tr data-id="${r['SR Number']}"><td>${r['SR Number']}</td><td>${r['SR Date']}</td><td>${r['Customer Name']}</td><td>${r['IB Serial Number']}</td><td><span class="type-badge ${r._category==='하드웨어'?'hardware':'software'}">${r._category}</span></td><td>${r['SR Type']}</td><td>${r['SR Creation Channel']}</td><td>${r['SR Problem Summary']}</td><td>${statusHtml(r['SR Status'])}</td></tr>`).join('')||'<tr><td colspan="9" class="empty">조건에 맞는 데이터가 없습니다.</td></tr>';bindRows('dashboard-data-table')}
function renderActiveCalls(){let rows=data.filter(r=>String(r['SR Status']||'').trim()==='진행중').sort((a,b)=>b._date-a._date);$('active-count').textContent=`${rows.length}건`;$('active-table').innerHTML=rows.map(r=>`<tr data-id="${r['SR Number']}"><td>${r['SR Number']}</td><td>${r['SR Date']}</td><td>${r['Customer Name']}</td><td>${r['IB Serial Number']}</td><td><span class="type-badge ${r._category==='하드웨어'?'hardware':'software'}">${r._category}</span></td><td>${r['SR Created By']||'-'}</td><td>${r['Actual CSE Name']||'-'}</td><td>${statusHtml(r['SR Status'])}</td><td>${r['SR Problem Summary']||'-'}</td></tr>`).join('')||'<tr><td colspan="9" class="empty">SR Status가 진행중인 콜이 없습니다.</td></tr>';bindRows('active-table')}
function renderRecent(){let rows=[...data].sort((a,b)=>b._date-a._date).slice(0,8);$('recent-table').innerHTML=rows.map(r=>`<tr data-id="${r['SR Number']}"><td>${r['SR Number']}</td><td>${r['SR Date']}</td><td>${r['Customer Name']}</td><td>${r['IB Serial Number']}</td><td>${r['SR Problem Summary']}</td><td>${statusHtml(r['SR Status'])}</td></tr>`).join('');bindRows('recent-table')}
function renderAll(){renderKPIs();renderChart();renderTypes();renderChannels();renderDashboardData();renderActiveCalls();renderRecent()}
function populateCustomers(){let names=[...new Set(data.map(r=>r['Customer Name']).filter(Boolean))].sort();$('customer-filter').innerHTML='<option value="all">전체 고객사</option>'+names.map(n=>`<option>${n}</option>`).join('')}
function parseCSV(text){text=text.replace(/^\uFEFF/,'');let delim=(text.split(/\r?\n/)[0].match(/\t/g)||[]).length>(text.split(/\r?\n/)[0].match(/,/g)||[]).length?'\t':',';let rows=[],row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){let ch=text[i],next=text[i+1];if(ch==='"'&&quoted&&next==='"'){cell+='"';i++;continue}if(ch==='"'){quoted=!quoted;continue}if(ch===delim&&!quoted){row.push(cell);cell='';continue}if((ch==='\n'||ch==='\r')&&!quoted){if(ch==='\r'&&next==='\n')i++;row.push(cell);cell='';if(row.some(x=>x.trim()))rows.push(row);row=[];continue}cell+=ch}if(cell||row.length){row.push(cell);rows.push(row)}return rows}
function validateRows(rows){let required=['SR Number','Customer Name','IB Serial Number','SR Date','SR Type'],missing=required.filter(c=>!rows[0].includes(c));if(missing.length)throw new Error(`필수 컬럼 누락: ${missing.join(', ')}`);let seen=new Set(),duplicates=0,invalid=0,parsed=[];rows.slice(1).forEach(vals=>{let r={};cols.forEach(c=>r[c]='');rows[0].forEach((h,i)=>{if(h)r[h]=String(vals[i]??'').trim()});if(!r['SR Number']&&!r['Customer Name'])return;if(seen.has(r['SR Number'])){duplicates++;return}seen.add(r['SR Number']);let d=new Date(r['SR Date']||r['SR Incident Date']);if(!r['SR Date']||Number.isNaN(d.getTime())){invalid++;return}parsed.push(decorate(r))});return {parsed,duplicates,invalid}}
const API='http://127.0.0.1:8765';
const SUPABASE_URL='https://lazobkwapjitomlarefa.supabase.co';
const SUPABASE_ANON_KEY='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxhem9ia3dhcGppdG9tbGFyZWZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTA2NDIzNTksImV4cCI6MjEwNjIxODM1OX0.B3x7b6WiuKQC10BGgAJOuYbYBqs33ivPQDZd81PxAS4';
function sbHeaders(auth=true){let token=auth?(localStorage.getItem('tsc_token')||SUPABASE_ANON_KEY):SUPABASE_ANON_KEY;return {'apikey':SUPABASE_ANON_KEY,'Authorization':`Bearer ${token}`,'Content-Type':'application/json','Prefer':'resolution=ignore-duplicates,return=minimal'}}
async function sbRequest(path,options={}){let res=await fetch(SUPABASE_URL+path,{...options,headers:{...sbHeaders(options.auth!==false),...(options.headers||{})}});if(!res.ok)throw new Error(await res.text());let text=await res.text();return text?JSON.parse(text):null}
async function saveCalls(rows,name){let existing=await sbRequest('/rest/v1/calls?select=sr_number');let existingNumbers=new Set((existing||[]).map(x=>x.sr_number));let duplicateExisting=rows.filter(row=>existingNumbers.has(row['SR Number'])).length;let freshRows=rows.filter(row=>!existingNumbers.has(row['SR Number']));let records=freshRows.map(row=>({'sr_number':row['SR Number']||`LOCAL-${crypto.randomUUID()}`,'payload':row,'source':name,'created_by':currentUser?.email||''}));if(records.length)await sbRequest('/rest/v1/calls',{method:'POST',body:JSON.stringify(records)});return {accepted:records.length,duplicateExisting}}
async function loadSavedCalls(){try{let result=await sbRequest('/rest/v1/calls?select=payload&order=created_at.desc');let rows=(result||[]).map(x=>x.payload);if(rows.length){data=rows.map(decorate);dataSource='Supabase 저장 데이터';populateCustomers();renderAll()}}catch(_){} }
async function uploadFile(file){let excel=/\.(xlsx|xls|xlsm)$/i.test(file.name),text=excel?await (await fetch('http://127.0.0.1:8765/api/upload',{method:'POST',headers:{'X-File-Name':'upload.xlsx'},body:file})).text():await file.text();let result=validateRows(parseCSV(text));if(!result.parsed.length)throw new Error('유효한 데이터 행이 없습니다.');let merged=new Map(data.map(r=>[r['SR Number'],r]));result.parsed.forEach(r=>merged.set(r['SR Number'],r));let allRows=[...merged.values()];let saved=await saveCalls(allRows,file.name);data=allRows;dataSource=`${file.name} 추가`;populateCustomers();renderAll();$('file-input').value='';alert(`새 파일 ${result.parsed.length}건 반영 · 신규 저장 ${saved.accepted}건 · 기존 중복 ${saved.duplicateExisting}건 · 파일 내 중복 ${result.duplicates}건 · 날짜 오류 ${result.invalid}건`)}
async function saveAudit(e){try{await sbRequest('/rest/v1/audit_logs',{method:'POST',body:JSON.stringify([{payload:e}])})}catch(_){} }
async function loadAudit(){try{let rows=await sbRequest('/rest/v1/audit_logs?select=payload&order=created_at.desc');if(Array.isArray(rows))audit=rows.map(x=>x.payload);renderAudit()}catch(_){} }
async function searchHistory(){let c=$('customer-filter').value,m=$('machine-filter').value.replace(/\D/g,''),cat=$('category-filter').value,p=$('period-filter').value,latest=latestDate(),start=p==='all'?new Date(0):new Date(latest.getFullYear(),latest.getMonth()-Number(p)+1,1),rows=data.filter(r=>(c==='all'||r['Customer Name']===c)&&(!m||r['IB Serial Number'].includes(m))&&(cat==='all'||r._category===(cat==='hardware'?'하드웨어':'소프트웨어'))&&r._date>=start);$('history-count').textContent=`조회 결과 ${rows.length}건`;$('history-table').innerHTML=rows.sort((a,b)=>b._date-a._date).map(r=>`<tr data-id="${r['SR Number']}"><td>${r['SR Number']}</td><td>${r['SR Date']}</td><td>${r['Customer Name']}</td><td>${r['IB Serial Number']}</td><td>${r._category}</td><td>${r['SR Type']}</td><td>${r['SR Problem Summary']}</td><td>${r['Actual CSE Name']}</td><td>${r['Debrief Header CSE Comments']}</td><td>${statusHtml(r['SR Status'])}</td></tr>`).join('')||'<tr><td colspan="10" class="empty">조건에 맞는 이력이 없습니다.</td></tr>';bindRows('history-table');let entry={time:new Date().toISOString(),user:currentUser?.email||'unknown',kind:m?'기계번호 이력 조회':'고객사 이력 조회',customer:c==='all'?'전체':c,machine:m||'전체',count:rows.length,download:'아니오'};audit.unshift(entry);renderAudit();saveAudit(entry)}
function renderAudit(){$('audit-table').innerHTML=audit.map(a=>`<tr><td>${new Date(a.time).toLocaleString('ko-KR')}</td><td>${a.user}</td><td>${a.kind}</td><td>${a.customer||'전체'}</td><td>${a.machine||'전체'}</td><td>${a.count}건</td><td>${a.download||'아니오'}</td></tr>`).join('')||'<tr><td colspan="7" class="empty">조회 로그가 없습니다.</td></tr>'}
function showView(v){document.querySelectorAll('.view').forEach(x=>x.classList.add('hidden'));$(v+'-view').classList.remove('hidden');document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===v));$('page-title').textContent=v==='dashboard'?'콜 분석 대시보드':v==='history'?'고객·기계 이력':'조회 감사 로그'}
async function login(email,password){let res=await fetch(SUPABASE_URL+'/auth/v1/token?grant_type=password',{method:'POST',headers:sbHeaders(false),body:JSON.stringify({email,password})});if(!res.ok)throw new Error('Supabase 로그인에 실패했습니다. Authentication 사용자를 확인해주세요.');let s=await res.json();currentUser={email:s.user?.email||email,id:s.user?.id,role:'operator'};localStorage.setItem('tsc_token',s.access_token);localStorage.setItem('tsc_user',JSON.stringify(currentUser));$('login-gate').classList.add('hidden');$('app-shell').classList.remove('locked');$('user-label').textContent=currentUser.email;await loadSavedCalls();await loadAudit();renderAll()}
function init(){data=fakeData();document.querySelectorAll('.nav-item,.text-btn').forEach(b=>b.onclick=()=>b.dataset.view&&showView(b.dataset.view));$('search-btn').onclick=searchHistory;$('chart-filter').onchange=renderChart;$('dashboard-category-filter').onchange=renderDashboardData;$('dashboard-channel-filter').onchange=renderDashboardData;$('upload-btn').onclick=()=>$('file-input').click();$('file-input').onchange=e=>uploadFile(e.target.files[0]).catch(err=>alert('업로드 실패: '+err.message));$('download-btn').onclick=()=>{let body=cols.join(',')+'\n'+data.map(r=>cols.map(c=>`"${String(r[c]||'').replaceAll('"','""')}"`).join(',')).join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+body],{type:'text/csv'}));a.download='tsc-calls.csv';a.click()};$('modal-close').onclick=()=>$('detail-modal').classList.add('hidden');$('detail-modal').onclick=e=>{if(e.target.id==='detail-modal')$('detail-modal').classList.add('hidden')};$('logout-btn').onclick=()=>{localStorage.clear();location.reload()};$('login-form').onsubmit=async e=>{e.preventDefault();$('login-message').textContent='로그인 중…';try{await login($('login-email').value,$('login-password').value)}catch(err){$('login-message').textContent=err.message}};let saved=localStorage.getItem('tsc_user');if(saved){currentUser=JSON.parse(saved);$('login-gate').classList.add('hidden');$('app-shell').classList.remove('locked');$('user-label').textContent=currentUser.email;loadSavedCalls();loadAudit()}populateCustomers();renderAll()}
init();
