create table if not exists public.calls (
  sr_number text primary key,
  payload jsonb not null,
  source text,
  created_by text,
  created_at timestamptz not null default now()
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  payload jsonb not null,
  created_at timestamptz not null default now()
);

alter table public.calls enable row level security;
alter table public.audit_logs enable row level security;

drop policy if exists "authenticated users can read calls" on public.calls;
create policy "authenticated users can read calls" on public.calls for select to authenticated using (true);
drop policy if exists "authenticated users can insert calls" on public.calls;
create policy "authenticated users can insert calls" on public.calls for insert to authenticated with check (true);
drop policy if exists "authenticated users can read audit logs" on public.audit_logs;
create policy "authenticated users can read audit logs" on public.audit_logs for select to authenticated using (true);
drop policy if exists "authenticated users can insert audit logs" on public.audit_logs;
create policy "authenticated users can insert audit logs" on public.audit_logs for insert to authenticated with check (true);
